### PR TITLE
Added JavaScript bubble/insertion sorts

### PR DESCRIPTION
**Pull request by gioboa**
I added also a js for test the algos -> xxx.test.js

### CODE REVIEW

**Comment by nikochiko** [comment]
Great job! Looks good to me! :rocket:

**Comment by gioboa** [comment]
I added also the docs for test the algos 👍

**Comment by nikochiko** [comment]
Awesome! One more thing, just check out https://github.com/nikochiko/cool-algos/pull/16. See if the styling changes are good (do a review / approve if it looks good), and we can merge that instead

**Comment by gioboa** [comment]
I've got prettier too... I think that clang format is different from the js one. 😢

**Pull request merged**
