### PR TITLE
Quick sort in js

### PR DESCRIPTION
**Pull request by rajlomror**
QuickSort algorithm in javascript.

### CODE REVIEW

**Comment by nikochiko** [comment]
Can you also add the test cases like here: https://github.com/nikochiko/cool-algos/pull/15 ?

**Comment by rajlomror** [comment]
> Can you also add the test cases like here: #15 ?

@nikochiko  Test case added for quicksort.

**Review by nikochiko — APPROVED** [review]
Great job!

**Comment by nikochiko** [comment]
Merged restyled version. Thanks for the contribution

**Pull request closed without merging**
