### PR TITLE
Merge sort in js

### PR DESCRIPTION
**Pull request by rajlomror**
Merge sort in js.
@nikochiko  Please review this.

### CODE REVIEW

**Review by nikochiko — CHANGES_REQUESTED** [review]
Can you add some cases to test the algorithm (like #15) ?

**Comment by rajlomror** [comment]
> Can you add some cases to test the algorithm (like #15) ?

@nikochiko test case added to the algorithm.

**Review by nikochiko — APPROVED** [review]
Nice work

**Comment by nikochiko** [comment]
Merged the restyled version

**Pull request closed without merging**
